{{- if and .Values.persistence.enabled -}}
{{- $serviceName := include "name" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $serviceName }}-pv-claim
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
