{{- $serviceName := include "name" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc | quote }}
  MYSQL_HOST: {{ printf "%s-%s" $serviceName .Values.azureVoteBack.service.name | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
