apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  namespace: vote
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: japaneast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: vote
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
